baseURL = 'https://kasdevTech.github.io/'
languageCode = 'en-us'
title = 'kasdevTech - Cloud | Azure | DevOps | AI'
theme = 'PaperMod'

[params]
  env = "production"
  title = "kasdevTech - Cloud | Azure | DevOps | AI"
  description = "Learn Azure, Terraform, FinOps, DevOps, and AI with real-world examples"
  author = "Kasi Suresh"
  ShowReadingTime = true
  ShowToc = true
  TocOpen = true
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
  ShowShareButtons = true
  ShowCodeCopyButtons = true
  ShowLastMod = true
  defaultTheme = "light"

  [params.profileMode]
    enabled = true
    title = "Kasi Suresh"
    subtitle = '''Cloud Architect | Azure | Terraform | FinOps | DevOps | AI'''
    imageUrl = "images/avatar.png"
    imageTitle = "Profile"
    imageWidth = 120
    imageHeight = 120
    buttons = [
      { name = "Blog", url = "/posts/" },
      { name = "About", url = "/about/" }
    ]

[params.homeInfoParams]
  Title = "Hi 👋, I’m Kasi Suresh"
  Content = '''Welcome to **kasdevTech** — a blog on Azure Cloud, Terraform, FinOps, DevOps, and AI 🚀'''

[[params.socialIcons]]
  name = "linkedin"
  url = "https://linkedin.com/in/YOUR_REAL_LINKEDIN"

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/KasdevTech"

[[params.socialIcons]]
  name = "twitter"
  url = "https://twitter.com/YOUR_TWITTER"

[menu]

  [[menu.main]]
    identifier = "azure"
    name = "Azure"
    url = "/Azure/"
    weight = 1

  [[menu.main]]
    identifier = "terraform"
    name = "Terraform"
    url = "/Terraform/"
    weight = 2

  [[menu.main]]
    identifier = "finops"
    name = "FinOps"
    url = "/Finops/"
    weight = 3

  [[menu.main]]
    identifier = "devops"
    name = "DevOps"
    url = "/Devops/"
    weight = 4

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/posts/"
    weight = 5

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 6

[markup]
  [markup.highlight]
    noClasses = false
