baseURL = 'https://kasdevTech.github.io/'
languageCode = 'en-us'
title = 'kasdevTech - Cloud | Azure | DevOps | AI'
theme = 'PaperMod'

[params]
  homeInfoParams = { Title = "Welcome to kasdevTech 🚀", Content = "Cloud | Azure | DevOps | Kubernetes | AI" }

[menu]
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 2
