baseURL = 'https://kasdevTech.github.io/'
languageCode = 'en-us'
title = 'kasdevTech - Cloud | Azure | DevOps | AI'
theme = 'PaperMod'

[params.homeInfoParams]
  Title = "Welcome to kasdevTech 🚀"
  Content = "Cloud | Azure | DevOps | Kubernetes | AI"

[menu]

  [[menu.main]]
    identifier = "azure"
    name = "Azure"
    url = "/Azure/"
    weight = 1

  [[menu.main]]
    identifier = "terraform"
    name = "Terraform"
    url = "/Terraform/"
    weight = 2

  [[menu.main]]
    identifier = "finops"
    name = "FinOps"
    url = "/Finops/"
    weight = 3

  [[menu.main]]
    identifier = "devops"
    name = "DevOps"
    url = "/Devops/"
    weight = 4

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/posts/"
    weight = 5

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 6
