baseURL = "https://kasdevtech.github.io/"
languageCode = "en-us"
title = "KasdevTech"
theme = "PaperMod"

enableRobotsTXT = true
enableInlineShortcodes = true
summaryLength = 70

[params]
  env = "production"
  author = "Kasi Suresh"
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowToc = true
  ShowCodeCopyButtons = true
  mainSections = ["Azure", "Terraform", "FinOps", "DevOps", "AI"]
  customCSS = ["css/custom.css"]

[params.homeInfoParams]
  Title = "Welcome to KasdevTech ☁️ "
  Content = "Cloud-native blogs on Azure, DevOps, FinOps & more."

[params.assets]
  logo = "images/kasdev.png"
  favicon = "images/favicon.ico"  

[menu]
  [[menu.main]]
  name = "Azure"
  url = "/azure/"
  weight = 1

  [[menu.main]]
  name = "DevOps"
  url = "/devops/"
  weight = 2

  [[menu.main]]
  name = "FinOps"
  url = "/finops/"
  weight = 3

  [[menu.main]]
  name = "Terraform"
  url = "/terraform/"
  weight = 4

  [[menu.main]]
  name = "AI"
  url = "/ai/"
  weight = 5

 [[menu.main]]
  name = "Finsight"
  url = "/finsight/"
  weight = 6

 [[menu.main]]
  name = "About"
  url = "/about/"
  weight = 7