baseURL = 'https://kasdevTech.github.io/'
languageCode = 'en-us'
title = 'KasdevTech - Cloud | Azure | DevOps | AI'
theme = 'PaperMod'

[params]
  env = "Production"
  title = "KasdevTech - Cloud | Azure | DevOps | AI"
  description = "Learn Azure, Terraform, FinOps, DevOps, and AI with real-world examples"
  author = "Kasi Suresh"
  googleAnalytics = "G-DGZYRTL4Y2"
  ShowReadingTime = true
  ShowToc = true
  TocOpen = true
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
  ShowShareButtons = true
  ShowCodeCopyButtons = true
  ShowLastMod = true
  defaultTheme = "auto"
  disableSpecial1stPost = false
  homeInfoMode = "auto"
  mainSections = ["posts", "AI", "Azure", "Terraform", "Devops", "Finops"]

[params.homeInfoParams]
  Title = "Welcome to KasdevTech 🚀"
  Content = '''A blog on Azure Cloud, Terraform, FinOps, DevOps, and AI'''

[[params.socialIcons]]
  name = "linkedin"
  url = "https://linkedin.com/in/kasi-suresh-992675177"

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/KasdevTech"

[menu]

  [[menu.main]]
    identifier = "azure"
    name = "Azure"
    url = "/Azure/"
    weight = 1

  [[menu.main]]
    identifier = "terraform"
    name = "Terraform"
    url = "/Terraform/"
    weight = 2

  [[menu.main]]
    identifier = "finops"
    name = "FinOps"
    url = "/Finops/"
    weight = 3

  [[menu.main]]
    identifier = "devops"
    name = "DevOps"
    url = "/Devops/"
    weight = 4

  [[menu.main]]
    identifier = "ai"
    name = "AI"
    url = "/AI/"
    weight = 5

  [[menu.main]]
    identifier = "blog"
    name = "All Posts"
    url = "/"
    weight = 6

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 7

[markup]
  [markup.highlight]
    noClasses = false
