name: Deploy Hugo site to GitHub Pages (main/docs)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.147.0'
          extended: true

      - name: Build Hugo site
        run: hugo --minify --destination docs

      - name: Commit and Push to docs folder
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs
          git commit -m "Deploy Hugo site to GitHub Pages" || echo "No changes to commit"
          git push origin main
