# .github/workflows/gh-pages.yml
name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.147.8'

      - name: Build Hugo site
        run: hugo --minify --destination docs

      - name: Deploy 🚀
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs
          git commit -m "Deploy Hugo site to GitHub Pages" || echo "No changes to commit"
          git push https://x-access-token:$GH_PAT@github.com/KasdevTech/kasdevTech.github.io.git main
